### ISSUE TITLE
Allow configuration of CARL without TLS

### ISSUE THREAD

**Issue by mirenz1** [eclipse-opendut/opendut#279]
Currently CARL requires to be configure with TLS, but for cloud cluster installations usually TLS termination is done in a reverse proxy (ingress) in front of the application.

- [x] Make TLS optional in CARL, so that it can be deactivated when an ingress is used in front of CARL

Relates to #100

**Comment by reimarstier** [comment]
While it is possible to configure this, it is generally discouraged to do so.

Technical background:
- https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#ssl-passthrough
- https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough
- Passing TLS through to the backend also prevents route based decisions on the ingress since the path information is TLS encrypted and only the server name indication may be decoded

**Comment by reimarstier** [comment]
This was implemented in commit 3ac971b08f2484b4cb1da9dd1eba48d15154fb65.
